### ISSUE TITLE
vim-lsp 2020

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/vim-lsp#624]
Let us this issue to discuss what we would like to work on for 2020.

Here are some of the high level

**Infra**
- [ ] Improve integration tests so that it tests with real language server. We should create a docker image so we don't have to be install language server during CI. Ok for this to run only in linux docker images as long as the utils such as file conversion runs in all OS and vim and neovim.
- [ ] Split LSP actions to separate files and provide common interface for them.
- [ ] https://github.com/prabirshrestha/vim-lsp/issues/121 call s:ensure_flush() after applying workspace edits
- [ ] https://github.com/prabirshrestha/vim-lsp/issues/125 `s:on_text_document_did_change` isn't fired in normal mode

**New Users**
- [ ] Create docker image for new users to try vim-lsp
- [x] embed async.vim??? This might make it easy for new users to get started.

**Features**
- [x] `lsp_highlight_references_enabled` is disabled by default since it doesn't use did changes and has perf impact. We should either ~~remove it completely~~ or fix the perf.
- [ ] allow users to use quickfix/loclist/ctrlp/fzf/denite/quickpick.vim. This needs to be done outside of vim-lsp.
- [x] TreeView support for call hierarchy/document symbols. We can most likely use this https://github.com/m-pilia/vim-yggdrasil as it can be embedded in vim-lsp.
- [ ] Live workspace symbol search. This needs on_change support which quickpick has it not sure about other fuzzy picker. Also should implement cancel. Should work similar to [quickpick-npm.vim](https://github.com/prabirshrestha/quickpick-npm.vim)
- [x] https://github.com/prabirshrestha/vim-lsp/issues/169 Allow to `LspDefinition` to open in split/vsplit/tab
- [ ] https://github.com/prabirshrestha/vim-lsp/issues/179 Add completion priority for each server or for vim-lsp globally
- [ ] https://github.com/prabirshrestha/vim-lsp/issues/186 Signs don't update after normal commands

**Perf improvements**
- [x] improve diff performance
- [ ] profile more bottleneck and improve perf.

**Comment by mattn** [comment]
+1 to add :LspAllDocumentDiagnostics. Some LS send diagnostics that are not opened files in Vim. But these are useful to notice errors.

**Comment by habamax** [comment]
Non stdio support (TCP) ?

**Comment by Isos9** [comment]
disable/enable virtual text for a specific diagnostic type. That would be nice.

**Comment by adaszko** [comment]
Thank you for your continued development of vim-lsp!  It's great!

What I miss the most is the ability to call its (autoload) functions from my VimScript code so that I can tailor its behavior better to my needs.  Commands like `LspDefinition` perform a side effect, which is of course jumping to a location where a identifier under the cursor is defined and also modifying the quickfix list.  What I would prefer instead (or perhaps in addition to it to preserve compatibility) is to have a VimScript functions like `lsp#get_definition_location(identifier)` exposed, that would return e.g. a dictionary/a list of dictionaries `{'filename': ..., 'lnum': ..., 'col': ...}` that I can interpret in my `.vimrc`.  It wouldn't touch either the cursor location or the quickfix list.

A similar argument goes for `LspReferences`: If I could call a function `lsp#get_references(identifier)` returning a list of locations, I could feed its output into my quick picker of choosing (i.e. FZF).

And so on for other commands: `LspWorkspaceSymbol`, `LspDocumentSymbol`, etc.

**Comment by martskins** [comment]
Just started using vim-lsp a few days ago, so forgive me if this is already there and I just couldn't find it, but I would love to see code lens support.

**Comment by randomgeek78** [comment]
I have created a docker image for my purposes - not shared yet. I can work on the docker image piece if it is not already taken up. What do you need for it?

**Comment by prabirshrestha** [comment]
@randomgeek78 feel free to start a new thread on docker and more than happy to have discussions there. Ideally I want someone to use `docker run vim-lsp` which comes with `vim`, `neovim`, `vim-lsp-settings`, `asyncomplete`, `asyncomplete-lsp.vim` so people can start trying out vim-lsp and experience it. There is https://github.com/prabirshrestha/vim-lsp/blob/master/minimal.vimrc which can be used as the base of vimrc I would like to see.

**Comment by randomgeek78** [comment]
Cool. Let me create a new thread. Tx

**Comment by idbrii** [comment]
@prabirshrestha You may want to add "pinned" label to this issue to prevent stale bot from closing.

**Comment by prabirshrestha** [comment]
integration tests are now supported via rust-analyzer. https://github.com/prabirshrestha/vim-lsp/pull/959

**Comment by prabirshrestha** [comment]
@idbrii any reason you want the issue to be still open. We are about to be done with 2020 and most of the items I would like to work on are done or have started.

**Comment by prabirshrestha** [comment]
@mattn I sent a PR to show the document diagnostics for all buffers at https://github.com/prabirshrestha/vim-lsp/pull/982. Let me know if that works. You can try it with `:LspDocumentDiagnostics --buffers=*`

**Comment by idbrii** [comment]
@prabirshrestha  I suggested keeping it open to make it easier to find. As a user it takes more digging to find the current priorities and looks like the task list isn't still relevant/active when it's closed.

But you're right, 2020 is nearly done, so no point in reopening.
